### PR TITLE
Katrina - wk1day3 HW

### PR DESCRIPTION
**Pull request by katshaze**
- difficulty 7/10 - really challenging but easier than the day before
- it was all very challenging but in particular I couldn't get the reverseString function to work.
- more info on having to declare variables inside/outside of functions before starting loops/if statements, like what is happening in the reverseString function (if I was approaching it correctly)
- took me about 3 hours

### CODE REVIEW

**Comment by aparkinbotswana** [comment]
You are doing well Katrina. Half the battle isn't coding. Its problem solving. Understanding how you nee d to break down a problem in small chunks and being able to program a solution from it. The way you are approaching each exercise is looking good. You are recognising where you need for loops and if statements and your data structures are look good too.

Where loops are concerned, depending on what your code is doing, you would usually want to declare your variables outside of it. If you declare a variable inside a function, then for every iteration of the loop, you are redefining your variable to whatever you set it as. If the case is that you want your code to add data to the variable and save the new data to that same variable for use elsewhere, it wont do that so long as you declare it inside the loop. it will keep reinitialising it. Hence why you should have it outside the loop. Again, as I said, it depends on your code. You very well want a variable that reinitialises to a specified default value at every iteration for whatever reason. Perhaps to check if a condition is met later on in the loop?

I think I understand you train of thought with the reverse string exercise. You are trying to use a for loop to iterate through each character of the string cause we can access it in a similar way to an array. That is a sound approach to the problem (errors in your code notwithstanding). Another way to approach this is to have a look into split() reverse() join(). see if you can understand how you could use those to come up with a solution.

**Comment by johnofsydney** [comment]
Hi Katrina

please excuse this chained version, but this is how you can reverse a string: string.split('').reverse().join('')



the inside / outside issue is called scope and really only practice makes this make sense. Joel has just been talking aboutn this just now (Friday 12.00)

In maxOfThree you could have used maxOfTwo in the code, eg:  maxOfThree(a, b, c) {
x = maxOfTwo(a, b) 
Y = maxOfTwo(c, a) 
return y }

With your vowelCheck you should make a test case 
Console.log(“e”)
Because “a” might give certain results just because it is the first element in the array… try it out and let me know how it goes.  

Hangman looks great, and super impressive to have done all the extensions. EXCELLENT!!

**Comment by johnofsydney** [comment]
Katrina - when Theo and I mark the homework, I start at the top of the list and work down, Theo starts art the bottom and works up. Congratulations you are the winner of the first time we have met in the middle!

**Comment by katshaze** [comment]
Thanks Theo, I'm about to review the reverse string exercise so will try
that out.

Kat

**Comment by katshaze** [comment]
Thanks John. Not sure if I'm getting back to you by replying to this email
- doesn't look like your email but giving it a go anyway.

Thanks for the feedback! Very clear and concise. :)

Re the vowel check - I did the test of the "e" as you suggested and you're
right - it didn't work! So I worked on it and figured out a kind of 'flag'
for if the loop hits a vowel, like so:

const vowelList = ["a","e","i","o","u"];
const vowelCheck = function(character) {
  let flagVowel;
  for (let i = 0; i < vowelList.length; i++) {
    if (character === vowelList[i]) {
      flagVowel = "yes";
    }
  }
  if (flagVowel === "yes") {
    return true;
  } else {
    return false;
  }
}

Seems to work now! Not sure if it's the most elegant solution though. :)

Re the reverse string exercise, is the reason we have to use the split and
join as well as reverse because the reverse method is only available for
using with arrays? There's no reverse method for strings? I think I have it
working now so thank you for that suggestion. :)

Thanks
Kat

**Pull request merged**
